#!/usr/bin/python3


def raise_exception_msg(message=""):
    #  Intentionally create a NameError who generate a message
    raise NameError(message)
